FROM python:3.7-alpine as ml-base

MAINTAINER Pascal Pellmont <github@ppo2.ch>
MAINTAINER Igor Dejanovic <igor.dejanovic@gmail.com>

COPY setup.* /app/
COPY pymlhelloworld /app/pymlhelloworld/
COPY LICENSE /app/
COPY Pipfile /app/
COPY Pipfile.lock /app/
COPY .coveragerc /app/
WORKDIR /app
ENV PIPENV_VENV_IN_PROJECT=True
RUN pip install pipenv && pipenv sync && pipenv install gunicorn==19.9.0
RUN pipenv install -e .


FROM ml-base as ml-testing

MAINTAINER Pascal Pellmont <github@ppo2.ch>
MAINTAINER Igor Dejanovic <igor.dejanovic@gmail.com>

COPY tests /app/tests
WORKDIR /app
RUN pipenv sync --dev
RUN pipenv run pytest --cov=pymlhelloworld tests
RUN pipenv run flake8 --teamcity train

FROM ml-testing as ml-training

MAINTAINER Pascal Pellmont <github@ppo2.ch>
MAINTAINER Igor Dejanovic <igor.dejanovic@gmail.com>

WORKDIR /app
# Train model


FROM ml-base as ml-production

MAINTAINER Pascal Pellmont <github@ppo2.ch>
MAINTAINER Igor Dejanovic <igor.dejanovic@gmail.com>

RUN adduser --system unicorn
USER unicorn
WORKDIR /app
EXPOSE 5000
CMD pipenv run gunicorn --workers=5 --bind=0.0.0.0:5000 pymlhelloworld.app:APP


